---

version: "3.9"
services:
  ucp-postgres:
    image: postgres:12-alpine
    container_name: ucp-postgres
    restart: always
    volumes:
      - ucp-postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ucp
      POSTGRES_USER: ucpuser
      POSTGRES_PASSWORD: ucppsw
  ucp-rabbitmq:
    image: rabbitmq:3.8-alpine
    container_name: ucp-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
  ucp-core:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ucp-core
    environment:
      WAIT_HOSTS: ucp-postgres:5432
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/ucp-core
    ports:
      - 8000:8000
    tty: true
    restart: on-failure
    depends_on:
      - ucp-postgres 
volumes:
  ucp-postgres-data:
networks:
  default:
    external:
      name: ucp-network
