# Generated by Django 3.2.4 on 2021-06-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=32)),
                ('last_name', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
