# Generated by Django 3.2.4 on 2021-06-09 14:03

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210609_1136'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['first_name'], name='customers_c_first_n_906a02_brin', pages_per_range=32),
        ),
    ]
